# 开发环境配置
server:
  port: 8090

# MyBatis配置
mybatis:
  # 搜索指定包别名(定义全局别名)
  typeAliasesPackage: org.peanutvideo.system.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml


# spring配置
spring:
  # 热部署配置
  thymeleaf:
    cache: true
    devtools:
      restart:
        enabled: true
        additional-paths: = src/main/java
  # 数据库配置
  datasource:
    name: peanutVideo
    url: jdbc:mysql://127.0.0.1/peanutvideo?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
    # druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
    level:
      org:
        peanutvideo:
          system:
            mapper: DEBUG

